---
title: "RoaryPCA"
output: 
  flexdashboard::flex_dashboard:
    theme: united
    orientation: columns
    social: menu
    source_code: embed
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(DT)
library(shiny)
library(ggplot2)
library(plotly)
library(dplyr)
library(ggthemes)
library(tidyverse)
library(kableExtra)
library(factoextra)
library(plotly)
library(FactoMineR)

dataset <- eventReactive(input$file1,{
      dataset <- read.table(input$file1$datapath, quote = "", check.names = FALSE, header = TRUE, sep = "\t")
    })
```

# Draw PCA plot from Roary "gene_presence_absence.Rtab" file

## Column {.sidebar}

```{r}

fileInput("file1", "Choose CSV File",
                    multiple = TRUE,
                    accept = c("text/csv",
                             "text/comma-separated-values,text/plain",
                             ".csv"))

# Theme
pc_list <- list("PC1" = 1, "PC2" = 2, "PC3" = 3, "PC4" = 4)

selectInput("pc_1","Select a Principal Component 1", choices = c(1:6), selected=1)
selectInput("pc_2","Select a Principal Component 2", choices = c(1:6), selected=2)
```

## Column {data-width=800, .tabset}

### Raw Data

```{r}
    renderTable({
      dataset <- dataset()
      dataset
    })
```

### Elbow plot (Genes)

```{r}


# Annotated_Gene_PA_df <- read.table("/data02/Analysis/Projects/2_CPE_Transmission/Tracking_Plasmid_Change/roary_out/annotation_gene_presence_absence.txt", quote = "", check.names = FALSE, header = TRUE, sep = "\t")
# #View(Annotated_Gene_PA_df)


renderPlot({
dataset <- dataset()
Annotated_Gene_PA_df <- dataset() %>% remove_rownames %>% column_to_rownames(var="Gene")
res.pca <- prcomp(Annotated_Gene_PA_df, scale = TRUE)
fviz_eig(res.pca)
})
    
# Annotated_Gene_PA_df  <- Annotated_Gene_PA_df %>% remove_rownames %>% column_to_rownames(var="Gene")
# res.pca <- prcomp(Annotated_Gene_PA_df, scale = TRUE)
# fviz_eig(res.pca)

```


### PCA (Genes)

```{r}

renderPlotly({
options(ggrepel.max.overlaps = 10)
  
dataset <- dataset()
Annotated_Gene_PA_df <- dataset() %>% remove_rownames %>% column_to_rownames(var="Gene")
res.pca <- prcomp(Annotated_Gene_PA_df, scale = TRUE)
# fviz_pca_ind(res.pca,
#              col.ind = "cos2", # Color by the quality of representation
#              gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"),
#              repel = TRUE     # Avoid text overlapping
# )

pc_1 <- as.integer(input$pc_1)
pc_2 <- as.integer(input$pc_2)
    
pca <- fviz_pca_ind(res.pca,c(pc_1,pc_2),
                   col.ind = "cos2", # Color by the quality of representation
                   gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"),
                   repel = TRUE     # Avoid text overlapping
)

ggly <- ggplotly(pca)
bggly <- plotly_build(ggly)
bggly$x$data[[1]]$text <- 
  with(pca$data, paste0("name: ", name, 
                        "</br></br>x: ", x, 
                        "</br>y: ", y, 
                        "</br>coord: ", coord, 
                        "</br>cos2: ", cos2, 
                        "</br>contrib: ", contrib))

bggly
})
```

### Elbow plot (Samples)

```{r}


# Annotated_Gene_PA_df <- read.table("/data02/Analysis/Projects/2_CPE_Transmission/Tracking_Plasmid_Change/roary_out/annotation_gene_presence_absence.txt", quote = "", check.names = FALSE, header = TRUE, sep = "\t")
# #View(Annotated_Gene_PA_df)


renderPlot({
dataset <- dataset()
Annotated_Gene_PA_df <- dataset() %>% remove_rownames %>% column_to_rownames(var="Gene")

#transpose data frame
Annotated_Gene_PA_df_t <- t(as.data.frame(Annotated_Gene_PA_df))
res.pca <- prcomp(Annotated_Gene_PA_df_t, scale = FALSE)
fviz_eig(res.pca)
})
    
# Annotated_Gene_PA_df  <- Annotated_Gene_PA_df %>% remove_rownames %>% column_to_rownames(var="Gene")
# res.pca <- prcomp(Annotated_Gene_PA_df, scale = TRUE)
# fviz_eig(res.pca)

```


### PCA (Samples)

```{r}
renderPlotly({
  
dataset <- dataset()
Annotated_Gene_PA_df <- dataset() %>% remove_rownames %>% column_to_rownames(var="Gene")

#transpose data frame
Annotated_Gene_PA_df_t <- t(as.data.frame(Annotated_Gene_PA_df))

options(ggrepel.max.overlaps = 10)

Sample_res.pca <- prcomp(Annotated_Gene_PA_df_t, scale = FALSE)
# fviz_pca_ind(res.pca,
#              col.ind = "cos2", # Color by the quality of representation
#              gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"),
#              repel = TRUE     # Avoid text overlapping
# )

pc_1 <- as.integer(input$pc_1)
pc_2 <- as.integer(input$pc_2)
    
Sample_pca <- fviz_pca_ind(Sample_res.pca,c(pc_1,pc_2),
                   col.ind = "cos2", # Color by the quality of representation
                   gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"),
                   repel = TRUE     # Avoid text overlapping
)

Sample_ggly <- ggplotly(Sample_pca)
Sample_bggly <- plotly_build(Sample_ggly)
Sample_bggly$x$data[[1]]$text <- 
  with(Sample_pca$data, paste0("name: ", name, 
                        "</br></br>x: ", x, 
                        "</br>y: ", y, 
                        "</br>coord: ", coord, 
                        "</br>cos2: ", cos2, 
                        "</br>contrib: ", contrib))

Sample_bggly
})
```
